/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GithubIcon: typeof import('./src/components/github-icon/index.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    NProgress: typeof import('naive-ui')['NProgress']
    RecordCard: typeof import('./src/components/record-card/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingIcon: typeof import('./src/components/setting-icon/index.vue')['default']
    Sider: typeof import('./src/components/layout/sider.vue')['default']
    Toggle: typeof import('./src/components/toggle/index.vue')['default']
    TopBar: typeof import('./src/components/layout/top-bar.vue')['default']
    WordCard: typeof import('./src/components/word-card/index.vue')['default']
  }
}
